ToDoAPP/models.py
from flask_login import UserMixin
from sqlalchemy.orm import relationship, Mapped, mapped_column
from sqlalchemy import Integer, String, Text, DateTime, Boolean

from ToDoAPP import db


class Task(db.Model):
    __tablename__ = "tasks"
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    author_id: Mapped[int] = mapped_column(Integer, db.ForeignKey("users.id"))
    author = relationship("User", back_populates="tasks")
    title: Mapped[str] = mapped_column(String, nullable=False)
    description: Mapped[str] = mapped_column(Text)
    deadline: Mapped[DateTime] = mapped_column(DateTime, nullable=False)
    startDate: Mapped[DateTime] = mapped_column(DateTime, nullable=False)
    endDate: Mapped[DateTime] = mapped_column(DateTime, nullable=True)
    status: Mapped[bool] = mapped_column(Boolean, default=False)


class User(UserMixin, db.Model):
    __tablename__ = "users"
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    email: Mapped[str] = mapped_column(String(100), unique=True)
    password: Mapped[str] = mapped_column(String(100))
    name: Mapped[str] = mapped_column(String(100))
    tasks = relationship("Task", back_populates="author")

ToDoAPP/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, DateTimeField, SubmitField, validators, PasswordField
from wtforms.validators import DataRequired, Length
from flask_ckeditor import CKEditorField


class ToDoForm(FlaskForm):
    titleField = StringField('Title', validators=[
        DataRequired(),
        Length(max=50),
        ])
    descriptionField = CKEditorField('Description')
    deadlineField = DateTimeField('Due', format='%d-%m-%Y %H:%M', validators=[DataRequired()], id='DateField')
    submitField = SubmitField(label="Add Task")


class EditForm(FlaskForm):
    titleField = StringField('Title', validators=[DataRequired()])
    descriptionField = CKEditorField('Description')
    deadlineField = DateTimeField('Deadline', format='%d-%m-%Y %H:%M')
    startField = DateTimeField('Start Date', format='%d-%m-%Y %H:%M')
    endField = DateTimeField('End Date', format='%d-%m-%Y %H:%M')
    submitField = SubmitField(label='Update Task')


class RegisterForm(FlaskForm):
    email = StringField("Email", validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired()])
    name = StringField("Name", validators=[DataRequired()])
    submit = SubmitField("Sign Me Up!")


class LoginForm(FlaskForm):
    email = StringField("Email", validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired()])
    submit = SubmitField("Let Me In!")

ToDoAPP/__init__.py
from flask import Flask
from flask_ckeditor import CKEditor
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_bootstrap import Bootstrap5
from pathlib import Path

from config import config

templates_dir = Path(__file__).resolve().parent / "templates"

db = SQLAlchemy()
migrate = Migrate()
login_manager = LoginManager()
bootstrap = Bootstrap5()
ckeditor = CKEditor()

def create_app():

    app = Flask(__name__, template_folder=templates_dir)
    app.config.from_object(config)

    # Inicjalizacja Flask-Login
    login_manager.init_app(app)
    login_manager.login_view = 'auth.login'  # Ustawienie domyślnego widoku logowania

    # Inicjalizacja SQLAlchemy i Flask-Migrate
    db.init_app(app)
    migrate.init_app(app, db)

    # Inicjalizacja Flask-Bootstrap5 i Flask-CKEditor
    bootstrap.init_app(app)
    ckeditor.init_app(app)


    with app.app_context():
        from ToDoAPP.models import User, Task
        db.create_all()

        @login_manager.user_loader
        def load_user(user_id):
            return User.query.get(str(user_id))

        from ToDoAPP.routes import routes_bp
        from ToDoAPP.tasks import tasks_bp
        from ToDoAPP.auth import auth_bp

        app.register_blueprint(routes_bp, url_prefix='/')
        app.register_blueprint(tasks_bp, url_prefix='/')
        app.register_blueprint(auth_bp, url_prefix='/')

    return app

ToDoAPP/routes/__init__.py
from flask import Blueprint

routes_bp = Blueprint('routes', __name__)

from ToDoAPP.routes import routes

ToDoAPP/routes/routes.py
from flask import render_template, request, redirect, url_for
from flask_login import current_user

from ToDoAPP import db
from ToDoAPP.routes import routes_bp
from ToDoAPP.models import User
from ToDoAPP.utils import send_email

# index route for front page
@routes_bp.route('/')
def index():
    return render_template('index.html')



@routes_bp.route('/faq')
def faq():
    return render_template('faq.html')


@routes_bp.route('/contact', methods=["GET", "POST"])
def contact():
    if request.method == "POST":
        name = request.form.get("name")
        email = request.form.get("email")
        body = request.form.get("message")
        send_email(email, name, body)
        return redirect(url_for('routes.contact'))
    if current_user.is_authenticated:
        result = db.session.execute(db.select(User).where(User.id == current_user.id))
        user = result.scalars().all()[0]

        return render_template('contact.html', user=user)
    else:
        return render_template('contact.html')

ToDoAPP/tasks/__init__.py
from flask import Blueprint

tasks_bp = Blueprint('tasks', __name__)

from ToDoAPP.tasks import tasks

ToDoAPP/templates/add.html
{% include "header.html" %}
{% from "bootstrap5/form.html" import render_form, render_field %}
{% block content %}

  {% if is_auth %}
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <form method="POST">
          {{ render_field(form.titleField, novalidate=True) }}
          {{ render_field(form.descriptionField, novalidate=True) }}

            <div class="d-flex align-items-center">
              <div class="col-lg-12 col-md-10 d-flex justify-content-between">
                {{ form.hidden_tag() }}
                {{ render_field(form.deadlineField, class="form-control", id="DateField") }}
                  <div class="align-self-center">
                    {{ render_field(form.submitField, novalidate=True, button_map={"submit": "primary"}) }}
                  </div>
              </div>
            </div>
          </form>
        </div>
  {% else %}

  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <p class="lead">Login for add new task. </p>
        <a type="button" class="btn btn-warning btn-lg me-2" href="{{ url_for('auth.login') }}">Login</a>
      </div>
  {% endif %}

{% endblock %}

{% include "footer.html" %}

ToDoAPP/templates/all_tasks.html
{% include "header.html" %}

{% block content %}

  <div class="container">
    <div class="row">
        {% if not tasks %}
            <div class="d-flex justify-content-center">
                <h4 class="task-title">There is no tasks to do.</h4>
            </div>
            <div class="d-flex justify-content-center">
                <a href="{{url_for('tasks.add_task') }}" class="nav-link px-2 text-body-secondary h4-link">Add new task.</a>
            </div>
            <div class="d-flex justify-content-center">
                <a href="{{url_for('tasks.finished_tasks') }}" class="nav-link px-2 text-body-secondary">See complited tasks.</a>
            </div>
        {% else %}
            <form class="task-preview" action="{{url_for('tasks.get_status')}}" method="post">
                    <div class="task mb-4 ">
                        <div class="container">
                            {% for task in tasks %}
                            <div class="row ml-auto">
                              <a class="h4-link" href="{{ url_for('tasks.edit_task', task_id=task.id)}}"> {{ task.title }}</a>
                            </div>
                            <div class="row">
                              <h5 class="task-subtitle col-3">{{ task.description }}</h5>
                            </div>
                            <div class="row">
                                <div class="col-3"> <b>Start:</b> {{task.startDate.strftime("%d-%m-%Y %H:%M")}} </div>
                                <div class="col-3"> <b>Deadline:</b> {{task.deadline.strftime("%d-%m-%Y %H:%M")}} </div>
                                {% if task.status %}
                                    {% if task.endDate %}
                                    <div class="col-3"> <b>Complete date:</b> {{task.endDate.strftime("%d-%m-%Y %H:%M")}} </div>
                                    {% else %}
                                    <div class="col-3"> <b>Complete date:</b> {{task.deadline.strftime("%d-%m-%Y %H:%M")}} </div>
                                    {% endif %}
                                    <div class="form-check form-switch col-3 ">
                                    <input class="form-check-input" type="checkbox" name="{{ task.id }}" id="flexSwitchCheckDisabled" checked disabled>
                                    <label class="form-check-label">   Status: completed </label>
                                    {% else %}
                                    <div class="col-3"> <b>Complete date:</b> </div>
                                    <div class="form-check form-switch col-3 ">
                                    <input class="form-check-input" type="checkbox" name="{{ task.id }}" id="flexSwitchCheckCheckedDisabled"  disabled>
                                    <label class="form-check-label" >   Status: not completed </label>
                                    {% endif %}
                                </div>
                            </div>

                    <!-- Divider-->
                    <hr class="my-4" />
                        {% endfor %}

            </form>
              {% endif %}
        </div>
    </div>
  </div>
</main>

{% endblock %}

{% include "footer.html" %}

ToDoAPP/templates/contact.html
{% include "header.html" %}

  <div class="jumbotron text-center">
    <div class="container">

          {% if msg_sent: %}
          <h1 class="display-4">Successfully sent your message</h1>
          {% else: %}
          <h1 class="display-4">Contact Me.</h1>
          {% endif %}
          <p class="lead">Have questions?</p>
    </div>
  </div>


<!-- Main Content-->
<main class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <p class="lead">
          Want to get in touch? Fill out the form below to send me a message and
          I will get back to you as soon as possible!
        </p>
        <div class="my-5">
          {% if user %}
          <form
            id="contactForm"
            name="sentMessage"
            action="{{ url_for('routes.contact') }}"
            method="post"
          >
            <div class="form-floating">
              <input
                class="form-control"
                id="name"
                name="name"
                type="text"
                placeholder="{{ user.name }}"
                value="{{ user.name }}"
                required
              />
              <label for="name"> Name </label>
            </div>
            <div class="form-floating">
              <input
                class="form-control"
                id="email"
                name="email"
                type="email"
                placeholder="{{ user.email }}"
                value="{{ user.email }}"
                required
              />
              <label for="email">Email</label>
            </div>

            {% else %}
            <form
            id="contactForm"
            name="sentMessage"
            action="Name"
            method="post"
          >
            <div class="form-floating">
              <input
                class="form-control"
                id="name"
                name="name"
                type="text"
                placeholder="Name..."
                required
              />
              <label for="name">Name</label>
            </div>
            <div class="form-floating">
              <input
                class="form-control"
                id="email"
                name="email"
                type="email"
                placeholder="Enter your email..."
                required
              />
              <label for="email">Email address</label>
            </div>
            {% endif %}

            <div class="form-floating">
              <textarea
                class="form-control"
                id="message"
                name="message"
                placeholder="Enter your message here..."
                required
                style="height: 12rem"
              ></textarea>
              <label for="message">Message</label>
            </div>
            <br />
            <button
              class="btn btn-primary text-uppercase"
              id="submitButton"
              type="submit"
            >
              Send
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</main>

{% include "footer.html" %}

ToDoAPP/templates/edit_task.html
{% block content %}
{% from "bootstrap5/form.html" import render_form, render_field %}
{% include "header.html" %}

<main class="mb-4">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <form method="POST">
          {{ render_field(form.titleField, novalidate=True) }}
          {{ render_field(form.descriptionField, novalidate=True) }}

          <div class="d-flex align-items-center">
            <div class="col-lg-12 col-md-10 d-flex justify-content-between">
                <input type="hidden" id="endDateValue" value="{{ task.endDate.strftime('%d-%m-%Y %H:%M') if task.endDate else '' }}">
                {{ form.hidden_tag() }}
                {{ render_field(form.startField, class="form-control", id="DateField", novalidate=True) }}
                {{ render_field(form.endField, class="form-control", id="endDateField", novalidate=True) }}
                {{ render_field(form.deadlineField, class="form-control", id="DateField", novalidate=True) }}
            </div>
          </div>

          <div class="d-flex align-items-center">
            <div class="col-lg-12 col-md-10 d-flex justify-content-between">
              <div class="form-check form-switch col-3 ">
                {% if task.status == True %}
                  <input class="form-check-input" type="checkbox" name="checkbox" id="flexSwitchCheckCheckedDisabled" onclick="toggleText()" checked>
                  <label id="displayText">Status: completed</label>
                {% else %}
                  <input class="form-check-input" type="checkbox" name="checkbox" id="flexSwitchCheckDisabled"  onclick="toggleText()">
                  <label id="displayText">Status: not completed</label>
                {% endif %}
              </div>
              {{ render_field(form.submitField, novalidate=True, button_map={"submit": "primary"}) }}
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</main>

{% include "footer.html" %}

{% endblock %}

ToDoAPP/templates/faq.html
{% include "header.html" %}

{% block content %}

        <main class="mb-4">
                <div class="container" id="faq">
                        <div class="row">
                                <h1>Frequently Asked Questions</h1>
                        </div>
                        <div class="row text-start">
                                <h2>What is this website about?</h2>
                                <p>This website is a task management platform designed to help you organize and track your daily tasks efficiently. Users can add, update, and view their tasks seamlessly.</p>
                        </div>

                        <div class="row text-start">
                                <h2>How do I create a new task?</h2>
                                <p>To create a new task, navigate to the "Add Task" section, fill in the required details such as title, description, deadline, and then click "Submit."</p>
                        </div>

                        <div class="row text-start">
                                <h2>How do I view my to-do list?</h2>
                                <p>You can view your to-do list by clicking on the "To-Do List" section. This will display all the tasks that are assigned to you and are currently incomplete.</p>
                        </div>

                        <div class="row text-start">
                                <h2>How can I edit a task?</h2>
                                <p>To edit  a task, go to the "To-Do List" section, find the task you want to modify, and click on the title of task.</p>
                        </div>

                        <div class="row text-start">
                                <h2>How do I mark a task as complete?</h2>
                                <p>In the "To-Do List" section, find the task you want to mark as complete and click on the "Complete" button. The task will be updated to show that it is finished.</p>
                        </div>

                        <div class="row text-start">
                                <h2>Why do I need to log in?</h2>
                                <p>Logging in ensures that your tasks are securely stored and only accessible to you. It also allows you to keep track of your progress and manage tasks effectively.</p>
                        </div>

                        <div class="row text-start">
                                <h2>What should I do if I encounter an error?</h2>
                                <p>If you encounter any issues or errors, please contact our support team via the contact form on the website. We will assist you as soon as possible.</p>
                        </div>
                </div>
        </main>

{% endblock %}

{% include "footer.html" %}

ToDoAPP/templates/finished_tasks.html
{% include "header.html" %}

{% block content %}

    <main class="mb-4">
      <div class="container">
        <div class="row">
            {% if not tasks %}
                <div >
                    <h4 class="task-title">There is no tasks completed.</h4>
                </div>
                <div class="d-flex justify-content-center">
                    <a href="{{url_for('tasks.to_do_list') }}" class="nav-link px-2 text-body-secondary">Show tasks to do.</a>
                </div>
            {% else %}
                <form class="task-preview" action="{{url_for('tasks.get_status')}}" method="post">
                    {% for task in tasks %}
                        <div class="task mb-4">
                            <div class="container">
                                <div class="row">
                                    <h4 class="task-title"> {{ task.title }}</h4>
                                </div>
                                <div class="row">
                                    <h5 class="task-subtitle">{{ task.description }}</h5>
                                </div>
                                <div class="row">
                                    <div class="col-4"> <b>Start:</b> {{task.startDate.strftime("%d-%m-%Y %H:%M")}} </div>
                                    <div class="col-4"> <b>Deadline:</b> {{task.deadline.strftime("%d-%m-%Y %H:%M")}} </div>
                                    {% if task.endDate %}
                                    <div class="col-4"> <b>Complete date:</b> {{task.endDate.strftime("%d-%m-%Y %H:%M")}} </div>
                                    {% else %}
                                    <div class="col-4"> <b>Complete date:</b> {{task.deadline.strftime("%d-%m-%Y %H:%M")}} </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <!-- Divider-->
                        <hr class="my-4" />
                    {% endfor %}
                </form>
            {% endif %}
            </div>
        </div>
      </div>
    </main>

{% endblock %}

{% include "footer.html" %}

ToDoAPP/templates/footer.html
            </div>
        </div>
    <footer class="py-3 my-4">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
          <li class="nav-item"><a href="{{url_for('routes.index') }}" class="nav-link px-2 text-body-secondary">Home</a></li>
          <li class="nav-item"><a href="{{url_for('tasks.to_do_list') }}" class="px-2 btn btn-warning btn">ToDoLIST</a></li>
          <li class="nav-item"><a href="{{url_for('tasks.all_tasks') }}" class="nav-link px-2 text-body-secondary">All Tasks</a></li>
          <li class="nav-item"><a href="{{url_for('tasks.finished_tasks') }}" class="nav-link px-2 text-body-secondary">Finished Tasks</a></li>
          <li class="nav-item"><a href="{{url_for('routes.faq') }}" class="nav-link px-2 text-body-secondary">FAQs</a></li>
          <li class="nav-item"><a href="{{url_for('routes.contact') }}" class="nav-link px-2 text-body-secondary">Contact</a></li>
        </ul>
        <p class="text-center text-body-secondary">© <span id="year"></span> Inc</p>
      </footer>

  </body>
</html>

ToDoAPP/templates/header.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    {% block styles %}
    <!-- Load Bootstrap-Flask CSS here -->
    {{ bootstrap.load_css() }}
    <!-- Link to the styles.css here to apply styling to all the child templates.-->
    {{ bootstrap.load_js() }}
    {% endblock %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">

    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="{{ url_for('static', filename='js/scripts.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>

    <title>{% block title %}ToDoAPP{% endblock %}</title>
  </head>
  <body>
      <header class="p-3 text-bg-dark">
          <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
              <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
              </a>

              <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{{url_for('routes.index') }}" class="btn btn-outline-light me-2">Home</a></li>
                <li><a href="{{url_for('tasks.to_do_list') }}" class="btn me-2 btn-warning btn">ToDoLIST</a></li>
                <li><a href="{{url_for('tasks.add_task') }}" class="btn btn-outline-light me-2">Add Task</a></li>
                <li><a href="{{url_for('tasks.all_tasks') }}" class="btn btn-outline-light me-2">All Tasks</a></li>
                <li><a href="{{url_for('tasks.finished_tasks') }}" class="btn btn-outline-light me-2">Finished Tasks</a></li>
              </ul>

              <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
                <input type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">
              </form>

              <div class="text-end">
                {% if not current_user.is_authenticated: %}
                <a type="button" class="btn btn-outline-light me-2" href="{{ url_for('auth.login') }}">Login</a>
                <a type="button" class="btn btn-warning" href="{{ url_for('auth.register') }}">Sign-up</a>
                {% else %}
                <a type="button" class="btn btn-outline-light me-2" href="{{ url_for('auth.logout') }}">Logout</a>
                {% endif %}
              </div>
            </div>
          </div>
        </header>
<main class="mb-4">
  <div class="jumbotron text-center">
    <div class="container">
      <h1 class="display-4">ToDoApp</h1>
        <p class="lead">Application to manage your tasks. </p>
          <hr class="my-4">

ToDoAPP/templates/index.html
{% include "header.html" %}

{% block content %}

<a class="btn btn-warning btn-lg" href="{{ url_for('tasks.to_do_list') }}" role="button">Show My ToDoList!</a>


{% endblock %}

{% include "footer.html" %}

ToDoAPP/templates/login.html
{% include "header.html" %}
{% from "bootstrap5/form.html" import render_form, render_field %}
{% block content %}

<main class="mb-4">
  <div class="container">
    <div class="row">
      <!-- Adding Flash message here for users trying to register twice -->
      {% with messages = get_flashed_messages() %}
      {% if messages %}
      {% for message in messages %}
      <p class="flash">{{ message }}</p>
      {% endfor %}
      {% endif %}
      {% endwith %}
      <div class="col-lg-8 col-md-10 mx-auto">
        <!--Rendering login form here-->
        {{render_form(form, novalidate=True, button_map={"submit": "primary"}) }}
      </div>
    </div>
  </div>
</main>

{% endblock %}

{% include "footer.html" %}

ToDoAPP/templates/register.html
{% include "header.html" %}
{% from "bootstrap5/form.html" import render_form, render_field %}
{% block content %}


<main class="mb-4">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
      <!--Rendering the registration form here-->
      {{render_form(form, novalidate=True, button_map={"submit": "primary"}) }}
      </div>
    </div>
  </div>
</main>

{% endblock %}

{% include "footer.html" %}

ToDoAPP/templates/to_do_list.html
{% include "header.html" %}

{% block content %}

    <main class="mb-4">
      <div class="container">
        <div class="row">
            {% if not tasks %}
                <div class="d-flex justify-content-center">
                    <h4 class="task-title">There is no tasks to do.</h4>
                </div>
                <div class="d-flex justify-content-center">
                    <a href="{{url_for('tasks.add_task') }}" class="nav-link px-2 text-body-secondary">Add new task.</a>
                </div>
                <div class="d-flex justify-content-center">
                    <a href="{{url_for('tasks.finished_tasks') }}" class="nav-link px-2 text-body-secondary">See completed tasks.</a>
                </div>
            {% else %}
                <form class="task-preview" action="{{url_for('tasks.get_status')}}" method="post">
                        <div class="task mb-4">
                            <div class="container">

                                {% for task in tasks %}
                                <div class="row">
                                  <h4 class="task-title"> {{ task.title }}</h4>
                                </div>

                                <div class="row">
                                  <h5 class="task-subtitle">{{ task.description }}</h5>
                                </div>

                                <div class="row">
                                    <div class="col-3"> <b>Start:</b> {{task.startDate.strftime("%d-%m-%Y %H:%M")}} </div>
                                    <div class="col-3"> <b>Deadline:</b> {{task.deadline.strftime("%d-%m-%Y %H:%M")}} </div>
                                    <div class="form-check form-switch col-6 d-flex justify-content-end">
                                        {% if not task.status %}
                                            <div class="form-check form-switch col-6">
                                                <input class="form-check-input" type="checkbox" name="{{ task.id }}" id="flexSwitchCheckCheckedDisabled" >
                                                    <div>
                                                        <label class="form-label" >Mark as complete</label>
                                                    </div>
                                            </div>
                                        {% endif %}
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        <!-- Divider-->
                        <hr class="my-4" />

                        <div>
                     <input class="btn btn-primary btn-sm" type="submit" value="Complete">
                    {% endif %}
                        </div>
                    </div>
            </form>
        </div>
      </div>
    </main>


{% endblock %}

{% include "footer.html" %}